/**
 * Word/phrase lexicon for Product Structure Latin suggestions.
 * Longest-match only — never letter-by-letter transliteration.
 */

export function normalizeFaKey(value) {
  return String(value || '')
    .replace(/ي/g, 'ی')
    .replace(/ك/g, 'ک')
    .replace(/[\u200c\u200d]/g, '')
    .replace(/[‌ـ]/g, '')
    .replace(/[()[\]{}«»"'،,._+/\\-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const RAW_PHRASES = [
  // Groups
  ['مقاطع فولادی', 'Carbon Steel'],
  ['استنلس استیل', 'Stainless Steel'],
  ['پیچ و مهره', 'Fasteners'],
  ['فرآورده های چوبی', 'Wood Products'],
  ['چوب طبیعی', 'Natural Wood'],
  ['چوب روسی', 'Russian Wood'],
  ['تخته زیرپایی روسی', 'Russian Scaffolding Footboard'],
  ['تخته زیرپایی', 'Scaffolding Footboards'],
  ['تخته چندلایه معمولی', 'Standard Plywood'],
  ['تخته چندلایه ضد رطوبت', 'Moisture-Resistant Plywood (MR)'],
  ['تخته چندلایه ضد آب', 'Waterproof / WBP Plywood'],
  ['تخته چندلایه لاکی', 'Film-Faced / Lacquered Formwork Plywood'],
  ['تخته چندلایه', 'Plywood'],
  ['اتصالات فولادی', 'Steel Fittings'],
  ['اتصالات', 'Fittings'],
  ['چوب', 'Timber'],
  ['مقاطع آلومینیومی', 'Aluminum Sections'],
  ['مقاطع آلومینیوم', 'Aluminum Sections'],
  ['محصولات آلومینیومی', 'Aluminum Products'],
  ['ورق آلومینیوم', 'Aluminum Sheet'],
  ['پروفیل آلومینیوم', 'Aluminum Profile'],
  ['لوله آلومینیوم', 'Aluminum Pipe'],
  ['میلگرد آلومینیوم', 'Aluminum Bar'],
  ['شمش آلومینیوم', 'Aluminum Billet'],
  ['تسمه آلومینیوم', 'Aluminum Flat'],
  ['نبشی آلومینیوم', 'Aluminum Angle'],
  ['فویل آلومینیوم', 'Aluminum Foil'],

  // Categories
  ['مفتول و محصولات مفتولی', 'Wire Products'],
  ['اتصالات جوشی مانیسمان', 'Welded Fittings - Seamless'],
  ['اتصالات جوشی درزدار', 'Welded Fittings - Seamed'],
  ['اتصالات فشار قوی و فورج', 'Forged High-Pressure Fittings'],
  ['اتصالات دنده ای', 'Threaded / Screwed Fittings'],
  ['انکر بولت و رول بولت', 'Anchor Bolts & Expansion Bolts'],
  ['نبشی و ناودانی', 'Angles and Channels'],
  ['تسمه فولادی', 'Steel Flat'],
  ['ورق سرد', 'Cold Rolled Sheet'],
  ['ورق گرم', 'Hot Rolled Sheet'],
  ['ورق', 'Sheet'],
  ['میلگرد استیل', 'Stainless Steel Round Bars'],
  ['ورق استیل', 'Stainless Steel Sheets'],
  ['لوله استیل', 'Stainless Steel Pipes & Tubes'],
  ['پروفیل استیل', 'Stainless Steel Profiles'],
  ['نبشی استیل', 'Stainless Steel Angles'],
  ['پیچ سرمته', 'Self-Drilling Screws'],
  ['چهارپهلو', 'Square Bar'],
  ['فلنج ها', 'Industrial Flanges'],
  ['فلنج‌ها', 'Industrial Flanges'],
  ['میلگرد', 'Rebar'],
  ['تیرآهن', 'Beam'],
  ['پروفیل', 'Profile'],
  ['لوله', 'Pipe'],
  ['پیچ', 'Bolt'],
  ['مهره', 'Nut'],
  ['واشر', 'Washer'],

  // Types — steel fittings (normalizeFaKey strips ZWNJ / parentheses)
  ['زانو ۱۸۰ درجه مانیسمان (U-Bend)', 'Welded Return Bend 180° (Seamless)'],
  ['زانو ۹۰ درجه مانیسمان', 'Welded Elbow 90° (Seamless)'],
  ['زانو ۴۵ درجه مانیسمان', 'Welded Elbow 45° (Seamless)'],
  ['زانو ۹۰ درجه درزدار', 'Welded Elbow 90° (Seamed)'],
  ['زانو ۴۵ درجه درزدار', 'Welded Elbow 45° (Seamed)'],
  ['سه راهی تبدیلی مانیسمان', 'Welded Reducing Tee (Seamless)'],
  ['سه راهی مساوی مانیسمان', 'Welded Equal Tee (Seamless)'],
  ['سه راهی تبدیلی درزدار', 'Welded Reducing Tee (Seamed)'],
  ['سه راهی مساوی درزدار', 'Welded Equal Tee (Seamed)'],
  ['تبدیل غیرهم‌مرکز مانیسمان', 'Welded Eccentric Reducer (Seamless)'],
  ['تبدیل هم‌مرکز مانیسمان', 'Welded Concentric Reducer (Seamless)'],
  ['تبدیل غیرهم‌مرکز درزدار', 'Welded Eccentric Reducer (Seamed)'],
  ['تبدیل هم‌مرکز درزدار', 'Welded Concentric Reducer (Seamed)'],
  ['تبدیل لبه‌دار (استب اند)', 'Stub End (Seamless)'],
  ['کپ مانیسمان (درپوش)', 'Welded Cap (Seamless)'],
  ['کپ درزدار (درپوش)', 'Welded Cap (Seamed)'],
  ['تردوولت / ساکوولت (اتصالات انشعابی)', 'Threadolet / Sockolet'],
  ['سه راهی تبدیلی ساکت‌ولد', 'Socket-Weld Reducing Tee'],
  ['سه راهی مساوی ساکت‌ولد', 'Socket-Weld Equal Tee'],
  ['کاپلینگ ساکت‌ولد (بوشن)', 'Socket-Weld Coupling'],
  ['مهره ماسوره ساکت‌ولد', 'Socket-Weld Union'],
  ['نیم‌بوشن ساکت‌ولد', 'Socket-Weld Half Coupling'],
  ['زانو ساکت‌ولد', 'Socket-Weld Elbow'],
  ['کپ ساکت‌ولد', 'Socket-Weld Cap'],
  ['زانو دنده‌ای فشار قوی', 'Forged Threaded Elbow'],
  ['سه راهی دنده‌ای فشار قوی', 'Forged Threaded Tee'],
  ['مغزی فشار قوی', 'Forged Hex Nipple'],
  ['چپقی دنده‌ای (زانو مغزی)', 'Threaded Street Elbow'],
  ['سه راهی تبدیلی دنده‌ای', 'Threaded Reducing Tee'],
  ['سه راهی مساوی دنده‌ای', 'Threaded Equal Tee'],
  ['تبدیل دنده‌ای (روپیچ توپیچ)', 'Threaded Bushing'],
  ['درپوش دنده‌ای (چهارگوش/شش‌گوش)', 'Threaded Plug / Cap'],
  ['مهره ماسوره دنده‌ای', 'Threaded Union'],
  ['بوشن دنده‌ای', 'Threaded Coupling / Socket'],
  ['زانو دنده‌ای', 'Threaded Elbow'],
  ['مغزی دنده‌ای', 'Hex Nipple'],
  ['فلنج گلودار جوشی', 'Welding Neck Flange (WNF)'],
  ['فلنج اسلیپون (روکار)', 'Slip-On Flange (SO)'],
  ['فلنج لبه‌دار', 'Lap Joint Flange'],
  ['فلنج لبه‌دار (لپ جوینت)', 'Lap Joint Flange'],
  ['فلنج ساکت‌ولد', 'Socket-Welding Flange'],
  ['فلنج دنده‌ای', 'Threaded Flange'],
  ['فلنج کور', 'Blind Flange (BF)'],

  // Types — fasteners
  ['رول بولت پروانه‌ای (مخصوص کناف)', 'Toggle Bolt / Hollow Wall Anchor'],
  ['واشر چهارگوش (مخصوص نبشی/تیرآهن)', 'Square Washer'],
  ['واشر ستاره‌ای (خورشیدی)', 'Internal / External Tooth Lock Washer'],
  ['پیچ سرمته‌ای واشردار (شیروانی)', 'Hex Washer Head Self-Drilling Screw'],
  ['پیچ سرمته‌ای سرتخت (خزینه)', 'Flat Head Self-Drilling Screw'],
  ['پیچ سرمته‌ای سرگرد (پانچی)', 'Pan Head Self-Drilling Screw'],
  ['پیچ سازه به سازه (نوک مته‌ای)', 'Framing Self-Drilling Screw'],
  ['مهره باریک (شش‌گوش نیم‌ارتفاع)', 'Hex Jam Nut'],
  ['مهره شش‌گوش سنگین (صنعتی)', 'Heavy Hex Nut'],
  ['مهره قفلی (کاسه نمدی)', 'Nylon Insert Lock Nut'],
  ['مهره کاسه‌دار (گنبدی)', 'Hex Cap / Acorn Nut'],
  ['مهره پروانه‌ای (خروسکی)', 'Wing Nut'],
  ['مهره شش‌گوش معمولی', 'Hex Nut'],
  ['مهره واشردار', 'Hex Flange Nut'],
  ['پیچ آلن با سر (استوانه‌ای)', 'Hex Socket Head Cap Screw'],
  ['پیچ آلن سرتخت (خزینه)', 'Countersunk Socket Screw'],
  ['استاد بولت (پیچ دو سر دنده)', 'Stud Bolt'],
  ['پیچ شش‌گوش آچاری', 'Hex Bolt'],
  ['پیچ آلن مغزی', 'Socket Set Screw'],
  ['پیچ متری', 'Threaded Rod'],
  ['پیچ اطاقی', 'Carriage Bolt'],
  ['واشر تخت معمولی', 'Plain / Flat Washer'],
  ['واشر تخت پهن', 'Fender Washer'],
  ['واشر فنری', 'Spring Split Lock Washer'],
  ['رول بولت غلافی معمولی', 'Sleeve Anchor'],
  ['انکر بولت ال‌شکل (کاشت بتن)', 'L-Shape Anchor Bolt'],
  ['انکر بولت ضربه‌ای (تکه‌ای)', 'Drop-In Anchor'],
  ['رول بولت HSA / غلافی سنگین', 'Heavy Duty Shield Anchor'],

  // Types — stainless steel
  ['ورق استیل سوپر دابلکس ۲۵۰۷', 'Super Duplex 2507 Stainless Steel Sheets'],
  ['لوله استیل سوپر دابلکس ۲۵۰۷', 'Super Duplex 2507 Stainless Steel Pipes & Tubes'],
  ['ورق استیل دابلکس ۲۲۰۵', 'Duplex 2205 Stainless Steel Sheets'],
  ['لوله استیل دابلکس ۲۲۰۵', 'Duplex 2205 Stainless Steel Pipes & Tubes'],
  ['ورق استیل ۳۰۴L', 'Stainless Steel 304L Sheets'],
  ['ورق استیل ۳۱۶L', 'Stainless Steel 316L Sheets'],
  ['ورق استیل ۴۳۰', 'Stainless Steel 430 Sheets'],
  ['ورق استیل ۳۲۱', 'Stainless Steel 321 Sheets'],
  ['ورق استیل ۳۱۰', 'Stainless Steel 310 Sheets'],
  ['لوله استیل ۳۰۴L', 'Stainless Steel 304L Pipes & Tubes'],
  ['لوله استیل ۳۱۶L', 'Stainless Steel 316L Pipes & Tubes'],
  ['لوله استیل ۴۳۰', 'Stainless Steel 430 Pipes & Tubes'],
  ['میلگرد استیل ۳۰۴', 'Stainless Steel 304 Round Bars'],
  ['میلگرد استیل ۳۱۶', 'Stainless Steel 316 Round Bars'],
  ['میلگرد استیل ۳۲۱', 'Stainless Steel 321 Round Bars'],
  ['میلگرد استیل ۴۲۰', 'Stainless Steel 420 Round Bars'],
  ['پروفیل استیل ۳۰۴', 'Stainless Steel 304 Profiles'],
  ['پروفیل استیل ۳۱۶', 'Stainless Steel 316 Profiles'],
  ['نبشی استیل ۳۰۴', 'Stainless Steel 304 Angles'],
  ['نبشی استیل ۳۱۶', 'Stainless Steel 316 Angles'],

  // Types
  ['ناودانی هم وزن اروپا', 'UNP Channel'],
  ['تیرآهن هاش سنگین HEB', 'HEB Beam'],
  ['تیرآهن هاش سبک HEA', 'HEA Beam'],
  ['تیرآهن هاش', 'H Beam'],
  ['تیرآهن IPE', 'IPE Beam'],
  ['نبشی بال نامساوی', 'Unequal Angle'],
  ['نبشی بال مساوی', 'Equal Angle'],
  ['ورق گالوانیزه رنگی', 'Pre-painted Galvanized Sheet'],
  ['ورق ضد سایش', 'Wear Resistant Sheet'],
  ['ورق ساده فولادی', 'Hot Rolled Sheet'],
  ['ورق A283', 'ASTM A283 Sheet'],
  ['ورق A36', 'ASTM A36 Sheet'],
  ['ورق A516', 'ASTM A516 Sheet'],
  ['ورق Ck45', 'Ck45 Sheet'],
  ['ورق اسید شویی', 'Pickled Sheet'],
  ['پروفیل چهارچوب', 'Door Frame Profile'],
  ['پروفیل گالوانیزه', 'Galvanized Profile'],
  ['پروفیل صنعتی', 'Heavy Profile'],
  ['پروفیل مبلی', 'Light Profile'],
  ['پروفیل زد', 'Z Profile'],
  ['لوله مانیسمان', 'Seamless Pipe'],
  ['لوله درزدار', 'Welded Pipe'],
  ['لوله تست گاز', 'Gas Test Pipe'],
  ['لوله تست آب', 'Water Test Pipe'],
  ['لوله API', 'API Pipe'],
  ['لوله جدار چاه', 'Well Casing Pipe'],
  ['لوله اسپیرال', 'Spiral Pipe'],
  ['لوله داربست', 'Scaffold Pipe'],
  ['لوله گالوانیزه', 'Galvanized Pipe'],
  ['میلگرد آلیاژی', 'Alloy Rebar'],
  ['میلگرد حرارتی', 'Thermal Rebar'],
  ['میلگرد آجدار', 'Deformed Rebar'],
  ['میلگرد ساده', 'Plain Rebar'],
  ['میلگرد بستر', 'Bed Rebar'],
  ['میلگرد کلاف', 'Wire Rod'],
  ['ورق گالوانیزه', 'Galvanized Sheet'],
  ['ورق آلیاژی', 'Alloy Sheet'],
  ['ورق آجدار', 'Chequered Sheet'],
  ['ورق روغنی', 'Cold Rolled Sheet'],
  ['ورق آتشخوار', 'Firebox Sheet'],
  ['ورق رنگی', 'Pre-painted Sheet'],
  ['ورق سیاه', 'Black Sheet'],
  ['ورق پانچ', 'Perforated Sheet'],
  ['نبشی لقمه', 'Clip Angle'],
  ['ناودانی', 'Channel'],
  ['سپری', 'Tee'],
  ['سیم فولادی', 'Steel Wire'],
  ['توری فولادی', 'Wire Mesh'],
  ['توری جوشی', 'Welded Wire Mesh'],
  ['توری حصاری', 'Fence Mesh'],
  ['توری مرغی', 'Hexagonal Mesh'],
  ['مش جوشی ساختمانی', 'Reinforcing Mesh'],

  // Attributes
  ['وزن واحد', 'Unit Weight'],
  ['طول سفارشی', 'Custom Length'],
  ['ضخامت', 'Thickness'],
  ['عرض بستر', 'Bed Width'],
  ['عرض', 'Width'],
  ['طول', 'Length'],
  ['طول ورق', 'Sheet Length'],
  ['چشمه', 'Mesh Opening'],
  ['سایز', 'Size'],
  ['قطر', 'Diameter'],
  ['ارتفاع', 'Height'],
  ['وزن', 'Weight'],
  ['استاندارد', 'Standard'],
  ['گرید', 'Grade'],
  ['شکل', 'Shape'],
  ['سطح', 'Surface'],
  ['پوشش', 'Coating'],
  ['رنگ', 'Color'],
  ['ابعاد', 'Dimensions'],
  ['مدل', 'Model'],
  ['بال ۱', 'Leg 1'],
  ['بال 1', 'Leg 1'],
  ['بال ۲', 'Leg 2'],
  ['بال 2', 'Leg 2'],

  // Units (display latin; codes are separate)
  ['متر مربع', 'Square Meter'],
  ['متر مکعب', 'Cubic Meter'],
  ['متر طول', 'Meter'],
  ['کیلوگرم', 'Kilogram'],
  ['شاخه', 'Branch'],
  ['کیلو', 'Kilogram'],
  ['گرم', 'Gram'],
  ['تن', 'Ton'],
  ['متر', 'Meter'],
  ['سانت', 'Centimeter'],
  ['عدد', 'Piece'],
  ['برگ', 'Sheet'],
  ['رول', 'Roll'],
  ['بسته', 'Pack'],
  ['جفت', 'Pair'],
  ['کلاف', 'Coil'],

  // Common catalog words
  ['فولادی', 'Steel'],
  ['فولاد', 'Steel'],
  ['آلومینیومی', 'Aluminum'],
  ['آلومینیوم', 'Aluminum'],
  ['آلومینیم', 'Aluminum'],
  ['الومینیوم', 'Aluminum'],
  ['الومینیم', 'Aluminum'],
  ['مس', 'Copper'],
  ['برنج', 'Brass'],
  ['چدن', 'Cast Iron'],
  ['استنلس', 'Stainless'],
  ['استیل', 'Stainless'],
  ['گالوانیزه', 'Galvanized'],
  ['مانیسمان', 'Seamless'],
  ['درزدار', 'Welded'],
  ['جوشی', 'Welded'],
  ['دنده ای', 'Threaded'],
  ['فشار قوی', 'High Pressure'],
  ['فورج', 'Forged'],
  ['آجدار', 'Deformed'],
  ['ساده', 'Plain'],
  ['آلیاژی', 'Alloy'],
  ['حرارتی', 'Thermal'],
  ['صنعتی', 'Industrial'],
  ['مبلی', 'Light'],
  ['چهارچوب', 'Door Frame'],
  ['بال مساوی', 'Equal'],
  ['بال نامساوی', 'Unequal'],
  ['هم وزن اروپا', 'European'],
  ['ضد سایش', 'Wear Resistant'],
  ['اسید شویی', 'Pickled'],
  ['آتشخوار', 'Firebox'],
  ['پانچ', 'Perforated'],
  ['روغنی', 'Cold Rolled'],
  ['رنگی', 'Pre-painted'],
  ['سیاه', 'Black'],
  ['گرم', 'Hot Rolled'],
  ['سرد', 'Cold Rolled'],
  ['سبک', 'Light'],
  ['سنگین', 'Heavy'],
  ['هاش', 'H'],
  ['نبشی', 'Angle'],
  ['تسمه', 'Flat'],
  ['مفتول', 'Wire'],
  ['محصولات مفتولی', 'Wire Products'],
  ['انکر بولت', 'Anchor Bolt'],
  ['رول بولت', 'Sleeve Anchor'],
  ['سرمته', 'Self Drilling'],
  ['وارداتی', 'Imported'],
  ['طبیعی', 'Natural'],
  ['فرآورده های', 'Products'],

  // Mills / brands (phrase, not letter map)
  ['ذوب آهن اصفهان', 'Esfahan Steel'],
  ['فولاد مبارکه', 'Mobarakeh Steel'],
  ['فولاد خراسان', 'Khorasan Steel'],
  ['گروه ملی', 'National Steel Group'],
  ['لوله سازی اهواز', 'Ahvaz Pipe'],
  ['جهان فولاد غرب', 'Jahan Steel West'],
  ['جهان سیرجان', 'Jahan Sirjan'],
  ['کاوه تیکمه داش', 'Kaveh Tikmeh Dash'],
  ['کاوه ایرانیان', 'Kaveh Iranian'],
  ['کاوه اروند', 'Kaveh Arvand'],
  ['کویر کاشان', 'Kavir Kashan'],
  ['امیرکبیر کاشان', 'Amirkabir Kashan'],
  ['امیرکبیر خزر', 'Amirkabir Khazar'],
  ['آذر گستر سدید', 'Azar Gostar Sadid'],
  ['فولاد یزد احرامیان', 'Yazd Ehramian Steel'],
  ['آتیه خلیج فارس', 'Atiyeh Persian Gulf'],
  ['ورق خودرو شهرکرد', 'Shahrekord Auto Sheet'],
  ['صبا فولاد زاگرس', 'Saba Zagros Steel'],
  ['صبا فولاد سمنان', 'Saba Semnan Steel'],
  ['فولاد آذربایجان', 'Azerbaijan Steel'],
  ['فولاد غرب آسیا', 'West Asia Steel'],
  ['نورد و تولید قطعات', 'NTF'],
  ['فولاد سپهر ایرانیان', 'Sepehr Iranian Steel'],
  ['لوله های دقیق کاوه ایرانیان', 'Kaveh Precision Pipe'],
  ['وارداتی چین', 'Imported China'],
  ['هفت الماس', 'Haft Almas'],
  ['نوین متین', 'Novin Matin'],
  ['آیین صنعت', 'Ayin Sanat'],
  ['راد همدان', 'Rad Hamedan'],
  ['صنعت بناب', 'Sanat Bonab'],
  ['ظفر بناب', 'Zafer Bonab'],
  ['سرمد ابرکوه', 'Sarmad Abarkuh'],
  ['بافق یزد', 'Bafq Yazd'],
  ['حدید سیرجان', 'Hadid Sirjan'],
  ['قائم رازی', 'Qaem Razi'],
  ['آذر امین', 'Azar Amin'],
  ['آناهیتا گیلان', 'Anahita Gilan'],
  ['فایکو', 'Faico'],
  ['کوثر اهواز', 'Kosar Ahvaz'],
  ['روهینا جنوب', 'Rohina South'],
  ['پرشین', 'Persian'],
  ['آریان فولاد', 'Arian Steel'],
  ['سیادن ابهر', 'Siadan Abhar'],
  ['پردیس سلفچگان', 'Pardis Salafchegan'],
  ['هیربد', 'Hirbod'],
  ['درپاد تبریز', 'Derpad Tabriz'],
  ['شاهرود', 'Shahrood'],
  ['فولاد نطنز', 'Natanz Steel'],
  ['فولاد بردسیر', 'Bardsir Steel'],
  ['فولاد ارگ تبریز', 'Arg Tabriz Steel'],
  ['خیام', 'Khayam'],
  ['ماهان', 'Mahan'],
  ['ناب تبریز', 'Nab Tabriz'],
  ['کادمیر', 'Kademir'],
  ['شکفته مشهد', 'Shakhefteh Mashhad'],
  ['ظهوریان مشهد', 'Zohourian Mashhad'],
  ['شرکت کیان پرشیا', 'Kian Persia'],
  ['کیان پرشیا', 'Kian Persia'],
  ['شرکت نورد و لوله تهران شرق', 'Tehran Shargh'],
  ['تهران شرق', 'Tehran Shargh'],
  ['شرکت فولاد گستر آتنا', 'Foolad Gostar Atena'],
  ['فولاد گستر آتنا', 'Foolad Gostar Atena'],
  ['شرکت تولیدی لوله و پروفیل کیهان', 'Keyhan Pipe'],
  ['کیهان', 'Keyhan Pipe'],
  ['شرکت نورد و لوله یاران', 'Yaran Pipe'],
  ['یاران', 'Yaran Pipe'],
  ['گروه تولیدی صنعتی کچو', 'Kacho'],
  ['کچو', 'Kacho'],
  ['گروه صنعتی سپنتا', 'Sepanta'],
  ['شرکت تولید لوله و پروفیل سپنتا', 'Sepanta'],
  ['سپنتا', 'Sepanta'],
  ['گروه صنعتی سپاهان', 'Sepahan'],
  ['سپاهان', 'Sepahan'],
  ['نورد و لوله قزوین', 'Qazvin Pipe'],
  ['اسپیرال اصفهان', 'Isfahan Spiral'],
  ['ایران اسپیرال', 'Iran Spiral'],
  ['آریا نورد خلیج فارس', 'Arya Navard Persian Gulf'],
  ['آریا نورد صنعت خلیج فارس', 'Arya Navard Persian Gulf'],
  ['لوله سازی خلیج فارس', 'Persian Gulf Pipe'],
  ['نورد و لوله صفا', 'Safa Rolling & Pipe'],
  ['تولید لوله و پوشش سلفچگان', 'SPPC'],
  ['نورد لوله و پوشش نیزار', 'Neyzar'],
  ['لوله و تجهیزات سدید', 'Sadid Pipe'],
  ['کالوپ', 'Kalup'],
  ['نیزار', 'Neyzar'],
  ['سدید', 'Sadid Pipe'],
  ['صفا', 'Safa'],
  ['اسپیرال', 'Spiral'],
  ['آونگان', 'Avangan'],
  ['منظومه', 'Manzoomeh'],
  ['یاوران زنجان', 'Yavaran Zanjan'],
  ['دهشیر یزد', 'Dehshir Yazd'],
  ['البرز غرب', 'Alborz West'],
  ['فولاد تهران', 'Tehran Steel'],
  ['تاراز', 'Taraz'],
  ['شهریار تبریز', 'Shahryar Tabriz'],
  ['دشتستان', 'Dashtestan'],
  ['فولاد گیلان', 'Gilan Steel'],
  ['اکسین اهواز', 'Oxin Ahvaz'],
  ['فولاد کاویان', 'Kavian Steel'],
  ['فولاد خرم آباد', 'Khorramabad Steel'],
  ['هاردوکس', 'Hardox'],
  ['آرتا', 'Arta'],
  ['پاسارگاد', 'Pasargad'],
  ['آسین ابهر', 'Asin Abhar'],
  ['البرز', 'Alborz'],

  // Places / mill fragments used as words
  ['اصفهان', 'Esfahan'],
  ['مبارکه', 'Mobarakeh'],
  ['خراسان', 'Khorasan'],
  ['آذربایجان', 'Azerbaijan'],
  ['خلیج فارس', 'Persian Gulf'],
  ['شهرکرد', 'Shahrekord'],
  ['سلفچگان', 'Salafchegan'],
  ['خرم آباد', 'Khorramabad'],
  ['تیکمه داش', 'Tikmeh Dash'],
  ['ابرکوه', 'Abarkuh'],
  ['سیرجان', 'Sirjan'],
  ['اهواز', 'Ahvaz'],
  ['کاشان', 'Kashan'],
  ['تبریز', 'Tabriz'],
  ['مشهد', 'Mashhad'],
  ['زنجان', 'Zanjan'],
  ['همدان', 'Hamedan'],
  ['گیلان', 'Gilan'],
  ['تهران', 'Tehran'],
  ['یزد', 'Yazd'],
  ['بناب', 'Bonab'],
  ['نطنز', 'Natanz'],
  ['بردسیر', 'Bardsir'],
  ['ابهر', 'Abhar'],
  ['سمنان', 'Semnan'],
  ['زاگرس', 'Zagros'],
  ['اروند', 'Arvand'],
  ['خزر', 'Khazar'],
  ['چین', 'China'],
  ['ترکیه', 'Turkey'],
  ['سوئد', 'Sweden'],
  ['جنوب', 'South'],
  ['غرب', 'West'],
  ['ملی', 'National'],
  ['گروه', 'Group'],
  ['شرکت', 'Co'],
  ['مجتمع', 'Complex'],
  ['صنایع', 'Industries'],
  ['نورد', 'Rolling'],
];

export const LATIN_STOPWORDS = new Set(['و', 'از', 'با', 'در', 'برای', 'یا', 'تا', 'به', 'که']);

export const LEXICON_KINDS = ['phrase', 'attribute_code', 'uom_code'];

const RAW_ATTRIBUTE_CODES = [
  ['وزن واحد', 'unit_weight'],
  ['طول سفارشی', 'custom_length'],
  ['ضخامت', 'thickness'],
  ['عرض', 'width'],
  ['طول', 'length'],
  ['طول ورق', 'sheet_length'],
  ['سایز', 'size'],
  ['قطر', 'diameter'],
  ['ارتفاع', 'height'],
  ['وزن', 'weight'],
  ['استاندارد', 'standard'],
  ['گرید', 'grade'],
  ['شکل', 'shape'],
  ['سطح', 'surface'],
  ['پوشش', 'coating'],
  ['رنگ', 'color'],
  ['ابعاد', 'dimensions'],
  ['فرمینگ', 'forming'],
];

const RAW_UOM_CODES = [
  ['کیلوگرم', 'KG'],
  ['کیلو', 'KG'],
  ['گرم', 'G'],
  ['تن', 'TON'],
  ['متر مربع', 'SQUARE_METER'],
  ['متر مکعب', 'CUBIC_METER'],
  ['متر طول', 'METER'],
  ['متر', 'METER'],
  ['سانت', 'CM'],
  ['شاخه', 'BRANCH'],
  ['عدد', 'PIECE'],
  ['برگ', 'SHEET'],
  ['رول', 'ROLL'],
  ['بسته', 'PACK'],
  ['جفت', 'PAIR'],
  ['کلاف', 'COIL'],
];

/** Bundled seed / mock-offline fallback. Live catalog is PostgreSQL (DDL-48). */
export function lexiconSeedEntries() {
  return [
    ...RAW_PHRASES.map(([faDisplay, latin]) => ({ faDisplay, latin, kind: 'phrase' })),
    ...RAW_ATTRIBUTE_CODES.map(([faDisplay, latin]) => ({ faDisplay, latin, kind: 'attribute_code' })),
    ...RAW_UOM_CODES.map(([faDisplay, latin]) => ({ faDisplay, latin, kind: 'uom_code' })),
  ];
}

export function catalogsFromEntries(entries) {
  const phrases = [];
  const attributeCodes = {};
  const uomCodes = {};
  for (const row of entries || []) {
    const fa = normalizeFaKey(row.faNormalized || row.fa || row.faDisplay);
    const latin = String(row.latin || '').trim();
    if (!fa || !latin || row.isActive === false) continue;
    if (row.kind === 'attribute_code') attributeCodes[fa] = latin;
    else if (row.kind === 'uom_code') uomCodes[fa] = latin;
    else phrases.push({ fa, latin });
  }
  phrases.sort((a, b) => b.fa.length - a.fa.length || a.fa.localeCompare(b.fa, 'fa'));
  return { phrases, attributeCodes, uomCodes };
}

export const BUNDLED_LATIN_CATALOGS = catalogsFromEntries(lexiconSeedEntries());

export const LATIN_PHRASES = BUNDLED_LATIN_CATALOGS.phrases;
export const ATTRIBUTE_CODES = BUNDLED_LATIN_CATALOGS.attributeCodes;
export const UOM_CODES = BUNDLED_LATIN_CATALOGS.uomCodes;
